# Generated by Django 5.1.4 on 2025-01-15 02:00

from django.db import migrations, models
from django.utils.timezone import now as timezone_now

class Migration(migrations.Migration):

    dependencies = [
        ('Wellness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=timezone_now),
            preserve_default=False,
        ),
    ]
