import React, { useState, useEffect } from 'react';
import { NavLink } from 'react-router-dom';
import './LandingPage.css';

function LandingPage() {
  const [visiblePopup, setVisiblePopup] = useState(null);

  useEffect(() => {
    document.body.className = 'home-screens';
    return () => {
      document.body.className = ''; // Reset class when unmounting
    };
  }, []);

  const closePopup = () => {
    setVisiblePopup(null);
  };

  return (
    <div className="landing-container">
      <h1 className="welcome-title">Welcome to your Health Ecosystem</h1>

      <div className="button-container">
        <NavLink to="/login" className="nav-button">
          Login
        </NavLink>
        <NavLink to="/signup" className="nav-button">
          Signup
        </NavLink>
      </div>

      <h2 className="explanation-message">
        By Signing Up or Logging In, the User agrees to{' '}
        <span
          className="click-here"
          onClick={() => setVisiblePopup('terms')}
        >
          Terms of Service
        </span>{' '}
        and{' '}
        <span
          className="click-here"
          onClick={() => setVisiblePopup('privacy')}
        >
          Privacy Policy
        </span>.
      </h2>

      {visiblePopup === 'terms' && (
        <div className="popup-overlay">
          <div className="popup">
            <h2>Terms of Service</h2>
            <p>1. Development Phase Disclaimer: The Health Economy (HE) web-based service is currently in its testing and development phase. By signing up for an account and/or logging in, you acknowledge that the service may contain bugs, errors, or inaccuracies.</p>
            <p>2. No Professional Advice: The content and outputs generated by HE are for informational purposes only and are not a substitute for professional advice, diagnosis, or treatment. Always consult a qualified professional before making health or wellness decisions.</p>
            <p>3. Limitation of Liability: By using HE, you agree to assume full responsibility for any actions taken based on the service's outputs. HE and its developers are not liable for any damages, losses, or injuries resulting from the use of this service.</p>
            <p>4. Feedback Request: We value your input! If you encounter issues or have suggestions, please use the feedback option in the Sidebar to help us improve.</p>
            <p>5. Data Privacy: HE is committed to protecting your data. By using the service, you agree to our privacy policy, which outlines how your information is stored and used.</p>
            <p>6. Updates to Terms: These terms may be updated periodically. Continued use of HE signifies your acceptance of the latest terms.</p>
            <button onClick={closePopup}>Close</button>
          </div>
        </div>
      )}

      {visiblePopup === 'privacy' && (
        <div className="popup-overlay">
          <div className="popup">
            <h2>Privacy Policy</h2>
            <p>1. Data Collection: We collect only the data you provide when signing up, logging in, or submitting feedback. This includes your name, email address, and any additional information shared through the platform.</p>
            <p>2. Data Usage: Your data is used solely to improve your experience with the Health Economy (HE) service, provide personalized features, and process feedback. We do not sell or share your data with third parties.</p>
            <p>3. Data Security: We implement industry-standard measures to protect your information from unauthorized access, misuse, or loss. However, no system is entirely secure, so we encourage users to exercise caution when sharing sensitive information.</p>
            <p>4. Cookies and Analytics: HE uses cookies and analytics tools to understand how users interact with the platform, helping us improve functionality. You can disable cookies in your browser settings if preferred.</p>
            <p>5. User Rights: You have the right to access, update, or delete your data. If you wish to make changes or have concerns, please contact us through the Feedback channel.</p>
            <p>6. Changes to This Policy: This policy may be updated from time to time. Continued use of the platform indicates your acceptance of the latest version.</p>
            <button onClick={closePopup}>Close</button>
          </div>
        </div>
      )}
    </div>
  );
}

export default LandingPage;
