# Generated by Django 5.1.4 on 2025-01-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_exercise_goal_profile_habit1_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='budget',
            field=models.TextField(blank=True, null=True),
        ),
    ]
