# Generated by Django 5.1.4 on 2025-01-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_apiresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='name',
            field=models.CharField(default='untitled list', max_length=255),
            preserve_default=False,
        ),
    ]
